Request to merge in 1.0.3 changes
fortinet-fortisoar/solution-pack-fortimanager-ztp-feature-examples pull request #14
Opened 2024-04-17 18:25 UTC by fortijames

_Do NOT Release before the v1.0.3 Framework is released_
https://github.com/fortinet-fortisoar/solution-pack-fortimanager-ztp-framework/pull/16

**1.0.3** 
 - New Profile that shows an example of a custom script. 
 - Modify the script `Create Loopback - lo0 - DeviceDB` to include `set ip {{devmeta.loopback0_ip}}/32`.

2024-04-19 07:53 UTC, cs-rohit-khune requested changes

2024-04-19 07:53 UTC, cs-rohit-khune commented on info.json
> +                "name": null,
"name" value should be *Attachments*

2024-04-19 07:53 UTC, cs-rohit-khune commented on info.json
> +                "name": null,
"name" value should be*Metafield Templates*

2024-04-19 07:53 UTC, cs-rohit-khune commented on info.json
> +                "name": null,
"name" value should be *Scripts*

2024-04-19 07:53 UTC, cs-rohit-khune commented on info.json
> +                "name": null,
"name" value should be *ZTP Profiles*

2024-05-24 12:49 UTC, fortijames commented
Changed the recordSets in info.json. Please let me know if there are any other pending changes preventing a merge.

2024-05-24 14:46 UTC, merged