Release/1.0.0 - solution-pack-fortimanager-ztp-feature-examples
fortinet-fortisoar/solution-pack-fortimanager-ztp-feature-examples pull request #2
Opened 2023-07-27 20:43 UTC by fortijames

Please review and merge for release.

This does require the pending pull request of the new FortiManager ZTP Flow Solution Pack ( https://github.com/fortinet-fortisoar/solution-pack-fortimanager-ztp-framework/pull/2 ).

2023-08-04 08:53 UTC, cs-rohit-khune requested changes

2023-08-04 08:53 UTC, cs-rohit-khune commented on info.json
> +    "publisher": "Community",
Update publisher to "Fortinet CSE"

2023-08-09 07:02 UTC, cs-rohit-khune commented
@fortijames Since this solution pack only includes demo records, it's recommended to use a scenario to create the same. [Refer to https://fortisoar.contenthub.fortinet.com//detail.html?entity=socSimulator&version=1.0.2&type=solutionpack]

2023-08-09 07:24 UTC, cs-rohit-khune commented
Please exclude the "modules" folder from the solution pack, as the "FortiManager ZTP Flow" pack already provides these modules.

2023-08-09 07:28 UTC, cs-rohit-khune commented on info.json
> +            "attachments": {
Please remove all the modules

2023-08-11 19:28 UTC, fortijames commented
> @fortijames Since this solution pack only includes demo records, it's recommended to use a scenario to create the same. [Refer to https://fortisoar.contenthub.fortinet.com//detail.html?entity=socSimulator&version=1.0.2&type=solutionpack]

I don't know if this will work very well for this framework. These records are not SOC Simulations. I might need some help going through what this would look like.

2023-08-16 07:29 UTC, cs-suyog-jinturkar approved these changes
Reviewed by Rohit. Approving here.

2023-08-16 07:29 UTC, merged